name: Build Electron App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
          - os: macos-latest
            arch: x64
            platform: mac
          - os: macos-latest
            arch: arm64
            platform: mac
          - os: ubuntu-latest
            arch: x64
            platform: linux
          - os: windows-latest
            arch: x64
            platform: win

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build code
        run: |
          pnpm electron-vite build
          cd gui/setting && npx vite build

      - name: Build Electron App
        run: pnpm run build --${{ matrix.platform }} --${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            dist/*.exe
            dist/*.deb
            dist/*.AppImage
            dist/*.dmg
          overwrite: true
          if-no-files-found: error

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: "artifacts/**/*"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TUBOSHU_TOKEN }}

